### PR TITLE
Uci2

### PR DESCRIPTION
**Pull request by Akababa**
It works on the old branch, minimal changes.
Here's a screenshot of the random model using the "demo" feature in arena:
capture

### CODE REVIEW

**Comment by francescobianco** [comment]
@Akababa Amazing UCI please marge soon @Zeta36

**Comment by Zeta36** [comment]
@Akababa, can you please write a little bit in readme.md about how to use your implementation in a GUI interface like Arena: nothing too much extensive just a couple of lines.

**Comment by Akababa** [comment]
Sure, do you mind if I clean up the old play_gui? Or do you prefer to keep that

**Comment by Zeta36** [comment]
Keep old by the moment, please.

**Pull request merged**
